schema_version: 1

context:
  version: "0.21.0"

package:
  name: aws-c-io
  version: ${{ version }}

source:
  url: https://github.com/awslabs/aws-c-io/archive/v${{ version }}.tar.gz
  sha256: 31232dd35995c9d5d535f3cf5ce7d561d680285a0e2a16318d4f0d4512b907c4

build:
  number: 0

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common
    - aws-c-cal
    - if: linux
      then: s2n
  run_exports:
    - ${{ pin_subpackage("aws-c-io", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libaws-c-io${SHLIB_EXT}
          - test -f $PREFIX/include/aws/io/io.h
      - if: win
        then:
          - if not exist %LIBRARY_INC%\\aws\\io\\io.h exit 1
          - if not exist %PREFIX%\\Library\\bin\\aws-c-io.dll exit 1
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C. It handles all IO and TLS work for application protocols.
  homepage: https://github.com/awslabs/aws-c-io

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
